#! /usr/bin/env bash
cd gmi/blog &&
    find . -name blog\*.gmi | while read filename
    do
        atomfilename=$(strip-extension $filename).atom
        echo atom: converting $filename to $atomfilename
        gmi-blog-atom \
            --author="T. Kurt Bond" --base="http://consp.org/blog/" \
            $filename >$atomfilename
    done
