#! /usr/bin/env bash

rsync ${DO_RSYNC_OPTIONS} -az --exclude=\*.gmi --exclude=\*~ --exclude=.~ --exclude='.#*' \
      --exclude='#*#' \
      --chmod=ugo=rwX --no-perms --no-group \
      --chown=tkb:nginx \
      gmi/ \
      tkb@consp.org:/var/www/consp.org/html
