#! /usr/bin/env bash

rsync ${DO_RSYNC_OPTIONS} -avz --exclude=\*.html --exclude=\*~ --exclude=.~ --exclude='.#*' \
      --exclude='#*#' \
      --chmod=ugo=rwX --no-perms --no-group \
      gmi/ \
      germinal@consp.org:consp.org/gmi
