#! /usr/bin/env bash

rsync -avvz --exclude=\*.gmi --exclude=\*~ --exclude=.~ --exclude='.#*' \
      --exclude='#*#' \
      --chmod=ugo=rwX --no-perms --no-group \
      gmi/ \
      tkb_consp@ssh.phx.nearlyfreespeech.net:/home/public
